- package.json
> chore(package): update babel-plugin-lodash to version 3.1.1

- package.json
> chore(package): update babel-plugin-lodash to version 3.1.2

- package.json
> chore(package): update babel-plugin-lodash to version 3.1.3

- package.json
> chore(package): update babel-plugin-add-module-exports to version 0.2.1

- package.json
> chore(package): update babel-plugin-lodash to version 3.1.4

- package.json
> chore(package): update babel-cli to version 6.9.0

- package.json
> chore(package): update bluebird to version 3.4.0

- package.json
> chore(package): update babel-core to version 6.9.1

- package.json
> chore(package): update babel-plugin-lodash to version 3.2.0

- package.json
> chore(package): update glob to version 7.0.5

- package.json
> chore(package): update babel-plugin-lodash to version 3.2.1

- package.json
> chore(package): update babel-plugin-lodash to version 3.2.2

- package.json
> chore(package): update babel-plugin-lodash to version 3.2.3

- package.json
> chore(package): update babel-plugin-lodash to version 3.2.4

- package.json
> chore(package): update babel-cli to version 6.11.4

- package.json
> chore(package): update lodash to version 4.14.1

- package.json
> chore(package): update babel-core to version 6.13.0

- package.json
> chore(package): update glob to version 7.1.0

- package.json
> chore(package): update lodash to version 4.16.1

- package.json
> chore(package): update glob to version 7.1.1

- package.json
> chore(package): update babel-core to version 6.18.0

- package.json
> chore(package): update babel-loader to version 6.2.8

- .eslintrc.js
- package-lock.json
- package.json
- src/index.js
- src/listing.js
- src/mapping.js
Hi;)
We introduce eslint and add rules from Lodash.
All codes fixed by eslint(`--fix`).
Thanks.
> Introduce eslint
